# Generated by Django 2.1.1 on 2018-09-12 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180129_0425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='tag',
            new_name='tags',
        ),
    ]
