# Generated by Django 2.1.1 on 2018-09-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_commets'),
    ]

    operations = [
        migrations.AddField(
            model_name='commets',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='commets',
            name='moderation',
            field=models.BooleanField(default=False),
        ),
    ]
